### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by skydig** [blitzarx1/netstrat#88]
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavio
r (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unal
igned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

**Comment by skydig** [comment]
sorry for late
I build under windows 10
following is trace 
F:\netstrat>cargo run
warning: dependency (petgraph) specified without providing a local path, Git repository, version, or workspace dependenc
y to use. This will be considered an error in future versions
warning: unused manifest key: dependencies.petgraph.vesion
   Compiling ntapi v0.3.7
   Compiling miow v0.3.7
   Compiling socket2 v0.4.4
   Compiling memoffset v0.6.5
   Compiling syn v1.0.92
   Compiling parking_lot_core v0.9.3
   Compiling num-traits v0.2.15
   Compiling crossbeam-utils v0.8.9
   Compiling http v0.2.7
   Compiling unicode-general-category v0.4.0
   Compiling idna v0.2.3
   Compiling indexmap v1.8.1
   Compiling native-tls v0.2.10
   Compiling deflate v1.0.0
   Compiling regex-automata v0.1.10
   Compiling httparse v1.7.1
   Compiling num-integer v0.1.45
   Compiling glutin_wgl_sys v0.1.5
   Compiling raw-window-handle v0.4.3
   Compiling schannel v0.1.19
   Compiling crossbeam-epoch v0.9.9
   Compiling instant v0.1.12
   Compiling error-code v2.3.1
   Compiling siphasher v0.3.10
   Compiling base64 v0.13.0
   Compiling unicode-ccc v0.1.2
   Compiling unicode-script v0.5.5
   Compiling windows_x86_64_msvc v0.37.0
   Compiling arrayvec v0.7.2
   Compiling once_cell v1.14.0
   Compiling ryu v1.0.9
   Compiling parking_lot v0.12.0
   Compiling float-cmp v0.9.0
   Compiling unicode-bidi-mirroring v0.1.0
   Compiling memmap2 v0.5.7
   Compiling try-lock v0.2.3
   Compiling xmlparser v0.13.3
   Compiling winit v0.27.2
   Compiling want v0.3.0
   Compiling png v0.17.5
   Compiling kurbo v0.8.3
   Compiling svgtypes v0.8.1
   Compiling fontdb v0.9.1
   Compiling clipboard-win v4.4.1
   Compiling url v2.2.2
   Compiling glutin_egl_sys v0.1.6
   Compiling roxmltree v0.14.1
   Compiling flate2 v1.0.24
   Compiling simplecss v0.2.1
   Compiling http-body v0.4.4
   Compiling rand_core v0.6.3
   Compiling data-url v0.1.1
   Compiling arrayref v0.3.6
error[E0793]: reference to packed field is unaligned
    --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\ntapi-0.3.7\src\ntexapi.rs:2783:
52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesse
s
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unal
igned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\ntapi-0.3.7\src\ntexapi.rs:2807:
25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesse
s
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unal
igned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling color_quant v1.1.0
   Compiling rctree v0.4.0
   Compiling arrayvec v0.5.2
   Compiling winreg v0.10.1
   Compiling encoding_rs v0.8.31
   Compiling widestring v0.5.1
   Compiling xmlwriter v0.1.0
   Compiling ppv-lite86 v0.2.16
   Compiling httpdate v1.0.2
   Compiling weezl v0.1.7
   Compiling crossbeam-queue v0.3.5
   Compiling pico-args v0.5.0
   Compiling unicode-vo v0.1.0
   Compiling tower-service v0.3.1
   Compiling into-attr v0.1.0
   Compiling dot-generator v0.1.0
   Compiling time v0.1.44
   Compiling remove_dir_all v0.5.3
   Compiling gif v0.11.4
   Compiling libloading v0.7.3
For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by blitzarx1** [comment]
Yeah it looks like a dependency issue. `ntapi` fails to build under windows. Checking...

**Comment by blitzarx1** [comment]
@skydig pull and try it now

**Comment by skydig** [comment]
compile is ok now，
but crash when running 


 INFO starting app
 INFO initing window net
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not fo
und" }', src\widgets\net_props\widget.rs:337:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src\windows\debug.rs:23:43
stack backtrace:
   0:     0x7ff7137b836c - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\sys_common\backtrace.r
s:44
   1:     0x7ff7137df36b - core::fmt::rt::Argument::fmt
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\fmt\rt.rs:138
   2:     0x7ff7137df36b - core::fmt::write
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\fmt\mod.rs:1094
   3:     0x7ff7137b33a9 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\io\mod.rs:1712
   4:     0x7ff7137b811b - std::sys_common::backtrace::_print
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\sys_common\backtrace.r
s:47
   5:     0x7ff7137b811b - std::sys_common::backtrace::print
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\sys_common\backtrace.r
s:34
   6:     0x7ff7137babd9 - std::panicking::default_hook::closure$1
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:269
   7:     0x7ff7137ba88f - std::panicking::default_hook
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:288
   8:     0x7ff7137bb0c6 - std::panicking::rust_panic_with_hook
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:691
   9:     0x7ff7137bafbd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:582
  10:     0x7ff7137b8f99 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::c
losure_env$0,never$>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\sys_common\backtrace.r
s:151
  11:     0x7ff7137bacd0 - std::panicking::begin_panic_handler
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:578
  12:     0x7ff7137ea865 - core::panicking::panic_fmt
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\panicking.rs:67
  13:     0x7ff7137eae73 - core::result::unwrap_failed
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\result.rs:1651
  14:     0x7ff7127d112a - enum2$<core::result::Result<tuple$<>,crossbeam_channel::err::SendError<alloc::vec::Vec<u8,all
oc::alloc::Global> > > >::unwrap<tuple$<>,crossbeam_channel::err::SendError<alloc::vec::Vec<u8,alloc::alloc::Global> > >

                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\core\src\result.rs:1076
  15:     0x7ff7127c2c54 - netstrat::windows::debug::impl$1::write
                               at F:\netstrat\src\windows\debug.rs:23
  16:     0x7ff7127e33db - std::io::Write::write_all<netstrat::windows::debug::BuffWriter>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\io\mod.rs:1572
  17:     0x7ff7127a6be4 - tracing_subscriber::fmt::writer::impl$11::write_all<netstrat::windows::debug::BuffWriter>
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\fmt\writer.rs:824
  18:     0x7ff71289d8cd - tracing_subscriber::fmt::fmt_layer::impl$11::on_event::closure$0<tracing_subscriber::registry
::sharded::Registry,tracing_subscriber::fmt::format::DefaultFields,tracing_subscriber::fmt::format::Format<tracing_subsc
riber::fmt::format::Full,tuple$<> >,std::s
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\fmt\fmt_layer.rs:898
  19:     0x7ff7127dd5b2 - std::thread::local::LocalKey<core::cell::RefCell<alloc::string::String> >::try_with<core::cel
l::RefCell<alloc::string::String>,tracing_subscriber::fmt::fmt_layer::impl$11::on_event::closure_env$0<tracing_subscribe
r::registry::sharded::Registry,tracing_sub
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\thread\local.rs:270
  20:     0x7ff7127dcd7e - std::thread::local::LocalKey<core::cell::RefCell<alloc::string::String> >::with<core::cell::R
efCell<alloc::string::String>,tracing_subscriber::fmt::fmt_layer::impl$11::on_event::closure_env$0<tracing_subscriber::r
egistry::sharded::Registry,tracing_subscri
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\thread\local.rs:246
  21:     0x7ff71289d687 - tracing_subscriber::fmt::fmt_layer::impl$11::on_event<tracing_subscriber::registry::sharded::
Registry,tracing_subscriber::fmt::format::DefaultFields,tracing_subscriber::fmt::format::Format<tracing_subscriber::fmt:
:format::Full,tuple$<> >,std::sync::mutex:
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\fmt\fmt_layer.rs:872
  22:     0x7ff7128607f0 - tracing_subscriber::layer::layered::impl$0::event<tracing_subscriber::fmt::fmt_layer::Layer<t
racing_subscriber::registry::sharded::Registry,tracing_subscriber::fmt::format::DefaultFields,tracing_subscriber::fmt::f
ormat::Format<tracing_subscriber::fmt::for
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\layer\layered.rs:116
  23:     0x7ff712860871 - tracing_subscriber::layer::layered::impl$0::event<tracing_core::metadata::LevelFilter,tracing
_subscriber::layer::layered::Layered<tracing_subscriber::fmt::fmt_layer::Layer<tracing_subscriber::registry::sharded::Re
gistry,tracing_subscriber::fmt::format::De
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\layer\layered.rs:115
  24:     0x7ff7127ee463 - tracing_subscriber::fmt::impl$2::event<tracing_subscriber::fmt::format::DefaultFields,tracing
_subscriber::fmt::format::Format<tracing_subscriber::fmt::format::Full,tuple$<> >,tracing_core::metadata::LevelFilter,st
d::sync::mutex::Mutex<netstrat::windows::d
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-subscriber-0.3.11\src\fmt\mod.rs:403
  25:     0x7ff71354b7b3 - tracing_core::dispatcher::Dispatch::event
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-core-0.1.31\src\dispatcher.rs:615
  26:     0x7ff713549270 - tracing_core::event::impl$0::dispatch::closure$0
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-core-0.1.31\src\event.rs:35
  27:     0x7ff71354af47 - tracing_core::dispatcher::get_default<tuple$<>,tracing_core::event::impl$0::dispatch::closure
_env$0>
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-core-0.1.31\src\dispatcher.rs:391
  28:     0x7ff713549232 - tracing_core::event::Event::dispatch
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-core-0.1.31\src\event.rs:34
  29:     0x7ff713533976 - egui_glow::painter::impl$3::drop::closure$0
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tracin
g-0.1.37\src\macros.rs:664
  30:     0x7ff7135335a6 - egui_glow::painter::impl$3::drop
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\egui_g
low-0.19.0\src\painter.rs:729
  31:     0x7ff71341ddff - core::ptr::drop_in_place<egui_glow::painter::Painter>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\core\src\ptr\mod.rs:497
  32:     0x7ff71343ae5e - eframe::native::run::glow_integration::GlowWinitApp::new
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:302
  33:     0x7ffe92a41030 - <unknown>
  34:     0x7ffe92a44ede - is_exception_typeof
  35:     0x7ffe92a4f3d0 - _C_specific_handler
  36:     0x7ffe92a4414c - is_exception_typeof
  37:     0x7ffe92a4fd11 - _CxxFrameHandler3
  38:     0x7ffe9de1245f - _chkstk
  39:     0x7ffe9dda0939 - RtlUnwindEx
  40:     0x7ffe92a4f89e - _C_specific_handler
  41:     0x7ffe92a42e05 - is_exception_typeof
  42:     0x7ffe92a43224 - is_exception_typeof
  43:     0x7ffe92a44248 - is_exception_typeof
  44:     0x7ffe92a4fd11 - _CxxFrameHandler3
  45:     0x7ffe9de123df - _chkstk
  46:     0x7ffe9ddc14a4 - RtlRaiseException
  47:     0x7ffe9ddc11f5 - RtlRaiseException
  48:     0x7ffe9b7fcb69 - RaiseException
  49:     0x7ffe92a466c0 - CxxThrowException
  50:     0x7ff7137cb57e - panic_unwind::real_imp::panic
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\panic_unwind\src\seh.rs:322
  51:     0x7ff7137cb57e - panic_unwind::__rust_start_panic
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\panic_unwind\src\lib.rs:103
  52:     0x7ff7137bb479 - std::panicking::rust_panic
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:741
  53:     0x7ff7137bb261 - std::panicking::rust_panic_with_hook
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:713
  54:     0x7ff7137bafbd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:582
  55:     0x7ff7137b8f99 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::c
losure_env$0,never$>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\sys_common\backtrace.r
s:151
  56:     0x7ff7137bacd0 - std::panicking::begin_panic_handler
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:578
  57:     0x7ff7137ea865 - core::panicking::panic_fmt
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\panicking.rs:67
  58:     0x7ff7137eae73 - core::result::unwrap_failed
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\core\src\result.rs:1651
  59:     0x7ff7127d0e85 - enum2$<core::result::Result<alloc::string::String,std::io::error::Error> >::unwrap<alloc::str
ing::String,std::io::error::Error>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\core\src\result.rs:1076
  60:     0x7ff71278e1f8 - netstrat::widgets::net_props::widget::NetProps::update_frame
                               at F:\netstrat\src\widgets\net_props\widget.rs:332
  61:     0x7ff71278af64 - netstrat::widgets::net_props::widget::NetProps::update_data
                               at F:\netstrat\src\widgets\net_props\widget.rs:194
  62:     0x7ff7127891fe - netstrat::widgets::net_props::widget::NetProps::new
                               at F:\netstrat\src\widgets\net_props\widget.rs:75
  63:     0x7ff7126f8eee - netstrat::windows::net::Net::new
                               at F:\netstrat\src\windows\net.rs:40
  64:     0x7ff7128b3fcc - netstrat::TemplateApp::new
                               at F:\netstrat\src\main.rs:71
  65:     0x7ff712782322 - netstrat::main::async_block$0::closure$0
                               at F:\netstrat\src\main.rs:122
  66:     0x7ff712844958 - core::ops::function::FnOnce::call_once<netstrat::main::async_block$0::closure_env$0,tuple$<re
f$<eframe::epi::CreationContext> > >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\core\src\ops\function.rs:250
  67:     0x7ff71343a4d0 - alloc::boxed::impl$47::call_once<tuple$<ref$<eframe::epi::CreationContext> >,dyn$<core::ops::
function::FnOnce<tuple$<ref$<eframe::epi::CreationContext> >,assoc$<Output,alloc::boxed::Box<dyn$<eframe::epi::App>,allo
c::alloc::Global> > > >,alloc::alloc::Glob
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\alloc\src\boxed.rs:1985
  68:     0x7ff71343ab92 - eframe::native::run::glow_integration::GlowWinitApp::new
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:281
  69:     0x7ff71343bdeb - eframe::native::run::glow_integration::run_glow::closure$0
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:458
  70:     0x7ff713435704 - eframe::native::run::with_event_loop::closure$0<eframe::native::run::glow_integration::run_gl
ow::closure_env$0>
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:84
  71:     0x7ff71343c59a - std::thread::local::LocalKey<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native:
:run::RequestRepaintEvent> > >::try_with<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRe
paintEvent> >,eframe::native::run::with_ev
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\thread\local.rs:270
  72:     0x7ff71343be9e - std::thread::local::LocalKey<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native:
:run::RequestRepaintEvent> > >::with<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRepain
tEvent> >,eframe::native::run::with_event_
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\thread\local.rs:246
  73:     0x7ff713435668 - eframe::native::run::with_event_loop<eframe::native::run::glow_integration::run_glow::closure
_env$0>
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:83
  74:     0x7ff71343bc2a - eframe::native::run::glow_integration::run_glow
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\native\run.rs:456
  75:     0x7ff713421742 - eframe::run_native
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\eframe
-0.19.0\src\lib.rs:172
  76:     0x7ff712782230 - netstrat::main::async_block$0
                               at F:\netstrat\src\main.rs:116
  77:     0x7ff7127e61c0 - tokio::runtime::park::impl$4::block_on::closure$0<enum2$<netstrat::main::async_block_env$0> >

                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\park.rs:283
  78:     0x7ff7127e5c43 - tokio::runtime::coop::with_budget
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\coop.rs:107
  79:     0x7ff7127e5c43 - tokio::runtime::coop::budget
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\coop.rs:73
  80:     0x7ff7127e5c43 - tokio::runtime::park::CachedParkThread::block_on<enum2$<netstrat::main::async_block_env$0> >
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\park.rs:283
  81:     0x7ff71281fb24 - tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<netstrat::main::async_block_env
$0> >
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\context.rs:315
  82:     0x7ff712819147 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<netstrat::main::async_b
lock_env$0> >
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\scheduler\multi_thread\mod.rs:66
  83:     0x7ff7128985a1 - tokio::runtime::runtime::Runtime::block_on<enum2$<netstrat::main::async_block_env$0> >
                               at C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\tokio-
1.28.1\src\runtime\runtime.rs:304
  84:     0x7ff7128b4717 - netstrat::main
                               at F:\netstrat\src\main.rs:116
  85:     0x7ff7128452db - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\core\src\ops\function.rs:250
  86:     0x7ff71286498e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\sys_common\backtrace.r
s:135
  87:     0x7ff71286498e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\sys_common\backtrace.r
s:135
  88:     0x7ff712831d81 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\rt.rs:166
  89:     0x7ff7137adf48 - std::rt::lang_start_internal::closure$2
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\rt.rs:148
  90:     0x7ff7137adf48 - std::panicking::try::do_call
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:485
  91:     0x7ff7137adf48 - std::panicking::try
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panicking.rs:449
  92:     0x7ff7137adf48 - std::panic::catch_unwind
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\panic.rs:142
  93:     0x7ff7137adf48 - std::rt::lang_start_internal
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library\std\src\rt.rs:148
  94:     0x7ff712831d5a - std::rt::lang_start<tuple$<> >
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252\library\std\src\rt.rs:165
  95:     0x7ff7128b47b9 - main
  96:     0x7ff7137e85bc - invoke_main
                               at d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  97:     0x7ff7137e85bc - __scrt_common_main_seh
                               at d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  98:     0x7ffe9da87604 - BaseThreadInitThunk
  99:     0x7ffe9ddc26a1 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\netstrat.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN
)

**Comment by blitzarx1** [comment]
Yeah the answer is in the [readme](https://github.com/blitzarx1/netstrat#depedencies): you need to have graphviz binary installed on your system https://graphviz.org/download/
